nginx:
  container_name: nginx-server  
  build: nginx/.
  ports:
    - "8001:80"
  volumes:
    - "./files:/www/data/files"

rclone:
  container_name: rclone-server    
  build: rclone/.
  command: bash
  ports:
    - "2595:2595"
  env_file:
    - ./rclone/env/config.env
  volumes:
    - "./files:/www/data/rsync"
  restart: always
  tty: true
